feat: Support unpacking in dict comprehensions
Add support for Unpacking in Comprehensions, which is introduced in Python 3.15 (PEP 798).

This PR also resolves the following failures in Python 3.15 environments type checking:
```
packages/griffelib/src/griffe/_internal/expressions.py:1264:16: error[invalid-argument-type] Argument to function `_build` is incorrect: Expected `AST`, found `expr | None`
```

ref: https://github.com/mkdocstrings/griffe/actions/runs/28114520110/job/83250363149#step:9:23